services:
  - type: web
    name: zoro-md
    env: node
    branch: main
    repo: https://github.com/zoro-md-vbot/zoro-md.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: ğŸ‘» áƒğ‘ï¼É€á´‡Ê€êª®  ğ‘†á¥±ğ‘¾ â€¢â¥¬Â³Â³Â³Â¯ğŸ‘»;https://i.imgur.com/CILQ4aC.mp4
      - key: WARN_COUNT
        value: 3
      - key: AUTO_STATUS_VIEWS
        value: false
      - key: MEDIA_DATA
        value: ÊŸÉªêœ±á´› á´á´‡É´á´œ;É€á´‡Ê€êª®  ğ‘†á¥±ğ‘¾ â€¢â¥¬Â³Â³Â³;https://i.imgur.com/VgxJeCm.jpeg
      - key: HANDLER
        value: /
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: STICKER_PACKNAME
        value:  ï¼É€á´‡Ê€êª®  ğ‘†á¥±ğ‘¾ â€¢â¥¬
      - key: AUDIO_DATA
        value: É€á´‡Ê€êª®  ğ‘†á¥±ğ‘¾ â€¢â¥¬Â³Â³Â³;https://i.imgur.com/VgxJeCm.jpeg
      - key: SUDO
        value: 919778158839
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
